language: python
python:
  - "3.6"

# Install dependencies
install:
  - pip install -r requirements.txt

# Set up PYTHONPATH
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# Run tests
script:
  - pytest